/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as DashboardDriverRouteRouteImport } from './routes/dashboard/driver/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardUserIndexRouteImport } from './routes/dashboard/user/index'
import { Route as DashboardDriverIndexRouteImport } from './routes/dashboard/driver/index'
import { Route as homeSuccessIndexRouteImport } from './routes/(home)/success/index'
import { Route as homeServicesIndexRouteImport } from './routes/(home)/services/index'
import { Route as homeDriversIndexRouteImport } from './routes/(home)/drivers/index'
import { Route as homeContactIndexRouteImport } from './routes/(home)/contact/index'
import { Route as homeAboutIndexRouteImport } from './routes/(home)/about/index'
import { Route as DashboardUserRecieptIndexRouteImport } from './routes/dashboard/user/$reciept/index'
import { Route as DashboardDriverNewDeliveriesIndexRouteImport } from './routes/dashboard/driver/new-deliveries/index'
import { Route as DashboardDriverMyDeliveriesIndexRouteImport } from './routes/dashboard/driver/my-deliveries/index'
import { Route as DashboardDriverBalanceIndexRouteImport } from './routes/dashboard/driver/balance/index'
import { Route as DashboardDriverActiveDeliveriesIndexRouteImport } from './routes/dashboard/driver/active-deliveries/index'
import { Route as DashboardAdminRevenueIndexRouteImport } from './routes/dashboard/admin/revenue/index'
import { Route as DashboardAdminPendingDriversIndexRouteImport } from './routes/dashboard/admin/pending-drivers/index'
import { Route as DashboardAdminPaymentsIndexRouteImport } from './routes/dashboard/admin/payments/index'
import { Route as DashboardAdminOrdersIndexRouteImport } from './routes/dashboard/admin/orders/index'
import { Route as DashboardAdminDriversIndexRouteImport } from './routes/dashboard/admin/drivers/index'
import { Route as homeServicesStorageIndexRouteImport } from './routes/(home)/services/storage/index'
import { Route as homeServicesFridgeRentalsIndexRouteImport } from './routes/(home)/services/fridge-rentals/index'
import { Route as homeServicesDeliveryIndexRouteImport } from './routes/(home)/services/delivery/index'
import { Route as homeauthSignUpIndexRouteImport } from './routes/(home)/(auth)/sign-up/index'
import { Route as homeauthSignInIndexRouteImport } from './routes/(home)/(auth)/sign-in/index'
import { Route as homeauthHraAdminIndexRouteImport } from './routes/(home)/(auth)/hra-admin/index'
import { Route as homeauthDriverRegistrationIndexRouteImport } from './routes/(home)/(auth)/driver-registration/index'
import { Route as homeauthDriverLoginIndexRouteImport } from './routes/(home)/(auth)/driver-login/index'
import { Route as DashboardDriverOrderDetailsOrderIdIndexRouteImport } from './routes/dashboard/driver/order-details/$orderId/index'
import { Route as DashboardDriverManageOrderOrderIdIndexRouteImport } from './routes/dashboard/driver/manage-order/$orderId/index'
import { Route as homeServicesStorageOrderIndexRouteImport } from './routes/(home)/services/storage/order/index'
import { Route as homeServicesFridgeRentalsOrderIndexRouteImport } from './routes/(home)/services/fridge-rentals/order/index'
import { Route as homeServicesDeliveryOrderIndexRouteImport } from './routes/(home)/services/delivery/order/index'
import { Route as DashboardAdmindetailsOrderDetailsOrderIdIndexRouteImport } from './routes/dashboard/admin/(details)/order-details/$orderId/index'
import { Route as DashboardAdmindetailsManageOrderOrderIdIndexRouteImport } from './routes/dashboard/admin/(details)/manage-order/$orderId/index'
import { Route as DashboardAdmindetailsDriverDetailsDriverIdIndexRouteImport } from './routes/dashboard/admin/(details)/driver-details/$driverId/index'

const homeRouteRoute = homeRouteRouteImport.update({
  id: '/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => homeRouteRoute,
} as any)
const DashboardDriverRouteRoute = DashboardDriverRouteRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/dashboard/user/',
  path: '/dashboard/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverIndexRoute = DashboardDriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDriverRouteRoute,
} as any)
const homeSuccessIndexRoute = homeSuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeServicesIndexRoute = homeServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeDriversIndexRoute = homeDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeContactIndexRoute = homeContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeAboutIndexRoute = homeAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => homeRouteRoute,
} as any)
const DashboardUserRecieptIndexRoute =
  DashboardUserRecieptIndexRouteImport.update({
    id: '/dashboard/user/$reciept/',
    path: '/dashboard/user/$reciept/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardDriverNewDeliveriesIndexRoute =
  DashboardDriverNewDeliveriesIndexRouteImport.update({
    id: '/new-deliveries/',
    path: '/new-deliveries/',
    getParentRoute: () => DashboardDriverRouteRoute,
  } as any)
const DashboardDriverMyDeliveriesIndexRoute =
  DashboardDriverMyDeliveriesIndexRouteImport.update({
    id: '/my-deliveries/',
    path: '/my-deliveries/',
    getParentRoute: () => DashboardDriverRouteRoute,
  } as any)
const DashboardDriverBalanceIndexRoute =
  DashboardDriverBalanceIndexRouteImport.update({
    id: '/balance/',
    path: '/balance/',
    getParentRoute: () => DashboardDriverRouteRoute,
  } as any)
const DashboardDriverActiveDeliveriesIndexRoute =
  DashboardDriverActiveDeliveriesIndexRouteImport.update({
    id: '/active-deliveries/',
    path: '/active-deliveries/',
    getParentRoute: () => DashboardDriverRouteRoute,
  } as any)
const DashboardAdminRevenueIndexRoute =
  DashboardAdminRevenueIndexRouteImport.update({
    id: '/revenue/',
    path: '/revenue/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminPendingDriversIndexRoute =
  DashboardAdminPendingDriversIndexRouteImport.update({
    id: '/pending-drivers/',
    path: '/pending-drivers/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminPaymentsIndexRoute =
  DashboardAdminPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminOrdersIndexRoute =
  DashboardAdminOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminDriversIndexRoute =
  DashboardAdminDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const homeServicesStorageIndexRoute =
  homeServicesStorageIndexRouteImport.update({
    id: '/services/storage/',
    path: '/services/storage/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const homeServicesFridgeRentalsIndexRoute =
  homeServicesFridgeRentalsIndexRouteImport.update({
    id: '/services/fridge-rentals/',
    path: '/services/fridge-rentals/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const homeServicesDeliveryIndexRoute =
  homeServicesDeliveryIndexRouteImport.update({
    id: '/services/delivery/',
    path: '/services/delivery/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const homeauthSignUpIndexRoute = homeauthSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeauthSignInIndexRoute = homeauthSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeauthHraAdminIndexRoute = homeauthHraAdminIndexRouteImport.update({
  id: '/(auth)/hra-admin/',
  path: '/hra-admin/',
  getParentRoute: () => homeRouteRoute,
} as any)
const homeauthDriverRegistrationIndexRoute =
  homeauthDriverRegistrationIndexRouteImport.update({
    id: '/(auth)/driver-registration/',
    path: '/driver-registration/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const homeauthDriverLoginIndexRoute =
  homeauthDriverLoginIndexRouteImport.update({
    id: '/(auth)/driver-login/',
    path: '/driver-login/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const DashboardDriverOrderDetailsOrderIdIndexRoute =
  DashboardDriverOrderDetailsOrderIdIndexRouteImport.update({
    id: '/order-details/$orderId/',
    path: '/order-details/$orderId/',
    getParentRoute: () => DashboardDriverRouteRoute,
  } as any)
const DashboardDriverManageOrderOrderIdIndexRoute =
  DashboardDriverManageOrderOrderIdIndexRouteImport.update({
    id: '/manage-order/$orderId/',
    path: '/manage-order/$orderId/',
    getParentRoute: () => DashboardDriverRouteRoute,
  } as any)
const homeServicesStorageOrderIndexRoute =
  homeServicesStorageOrderIndexRouteImport.update({
    id: '/services/storage/order/',
    path: '/services/storage/order/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const homeServicesFridgeRentalsOrderIndexRoute =
  homeServicesFridgeRentalsOrderIndexRouteImport.update({
    id: '/services/fridge-rentals/order/',
    path: '/services/fridge-rentals/order/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const homeServicesDeliveryOrderIndexRoute =
  homeServicesDeliveryOrderIndexRouteImport.update({
    id: '/services/delivery/order/',
    path: '/services/delivery/order/',
    getParentRoute: () => homeRouteRoute,
  } as any)
const DashboardAdmindetailsOrderDetailsOrderIdIndexRoute =
  DashboardAdmindetailsOrderDetailsOrderIdIndexRouteImport.update({
    id: '/(details)/order-details/$orderId/',
    path: '/order-details/$orderId/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdmindetailsManageOrderOrderIdIndexRoute =
  DashboardAdmindetailsManageOrderOrderIdIndexRouteImport.update({
    id: '/(details)/manage-order/$orderId/',
    path: '/manage-order/$orderId/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdmindetailsDriverDetailsDriverIdIndexRoute =
  DashboardAdmindetailsDriverDetailsDriverIdIndexRouteImport.update({
    id: '/(details)/driver-details/$driverId/',
    path: '/driver-details/$driverId/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/driver': typeof DashboardDriverRouteRouteWithChildren
  '/about': typeof homeAboutIndexRoute
  '/contact': typeof homeContactIndexRoute
  '/drivers': typeof homeDriversIndexRoute
  '/services': typeof homeServicesIndexRoute
  '/success': typeof homeSuccessIndexRoute
  '/dashboard/driver/': typeof DashboardDriverIndexRoute
  '/dashboard/user': typeof DashboardUserIndexRoute
  '/driver-login': typeof homeauthDriverLoginIndexRoute
  '/driver-registration': typeof homeauthDriverRegistrationIndexRoute
  '/hra-admin': typeof homeauthHraAdminIndexRoute
  '/sign-in': typeof homeauthSignInIndexRoute
  '/sign-up': typeof homeauthSignUpIndexRoute
  '/services/delivery': typeof homeServicesDeliveryIndexRoute
  '/services/fridge-rentals': typeof homeServicesFridgeRentalsIndexRoute
  '/services/storage': typeof homeServicesStorageIndexRoute
  '/dashboard/admin/drivers': typeof DashboardAdminDriversIndexRoute
  '/dashboard/admin/orders': typeof DashboardAdminOrdersIndexRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsIndexRoute
  '/dashboard/admin/pending-drivers': typeof DashboardAdminPendingDriversIndexRoute
  '/dashboard/admin/revenue': typeof DashboardAdminRevenueIndexRoute
  '/dashboard/driver/active-deliveries': typeof DashboardDriverActiveDeliveriesIndexRoute
  '/dashboard/driver/balance': typeof DashboardDriverBalanceIndexRoute
  '/dashboard/driver/my-deliveries': typeof DashboardDriverMyDeliveriesIndexRoute
  '/dashboard/driver/new-deliveries': typeof DashboardDriverNewDeliveriesIndexRoute
  '/dashboard/user/$reciept': typeof DashboardUserRecieptIndexRoute
  '/services/delivery/order': typeof homeServicesDeliveryOrderIndexRoute
  '/services/fridge-rentals/order': typeof homeServicesFridgeRentalsOrderIndexRoute
  '/services/storage/order': typeof homeServicesStorageOrderIndexRoute
  '/dashboard/driver/manage-order/$orderId': typeof DashboardDriverManageOrderOrderIdIndexRoute
  '/dashboard/driver/order-details/$orderId': typeof DashboardDriverOrderDetailsOrderIdIndexRoute
  '/dashboard/admin/driver-details/$driverId': typeof DashboardAdmindetailsDriverDetailsDriverIdIndexRoute
  '/dashboard/admin/manage-order/$orderId': typeof DashboardAdmindetailsManageOrderOrderIdIndexRoute
  '/dashboard/admin/order-details/$orderId': typeof DashboardAdmindetailsOrderDetailsOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/': typeof homeIndexRoute
  '/about': typeof homeAboutIndexRoute
  '/contact': typeof homeContactIndexRoute
  '/drivers': typeof homeDriversIndexRoute
  '/services': typeof homeServicesIndexRoute
  '/success': typeof homeSuccessIndexRoute
  '/dashboard/driver': typeof DashboardDriverIndexRoute
  '/dashboard/user': typeof DashboardUserIndexRoute
  '/driver-login': typeof homeauthDriverLoginIndexRoute
  '/driver-registration': typeof homeauthDriverRegistrationIndexRoute
  '/hra-admin': typeof homeauthHraAdminIndexRoute
  '/sign-in': typeof homeauthSignInIndexRoute
  '/sign-up': typeof homeauthSignUpIndexRoute
  '/services/delivery': typeof homeServicesDeliveryIndexRoute
  '/services/fridge-rentals': typeof homeServicesFridgeRentalsIndexRoute
  '/services/storage': typeof homeServicesStorageIndexRoute
  '/dashboard/admin/drivers': typeof DashboardAdminDriversIndexRoute
  '/dashboard/admin/orders': typeof DashboardAdminOrdersIndexRoute
  '/dashboard/admin/payments': typeof DashboardAdminPaymentsIndexRoute
  '/dashboard/admin/pending-drivers': typeof DashboardAdminPendingDriversIndexRoute
  '/dashboard/admin/revenue': typeof DashboardAdminRevenueIndexRoute
  '/dashboard/driver/active-deliveries': typeof DashboardDriverActiveDeliveriesIndexRoute
  '/dashboard/driver/balance': typeof DashboardDriverBalanceIndexRoute
  '/dashboard/driver/my-deliveries': typeof DashboardDriverMyDeliveriesIndexRoute
  '/dashboard/driver/new-deliveries': typeof DashboardDriverNewDeliveriesIndexRoute
  '/dashboard/user/$reciept': typeof DashboardUserRecieptIndexRoute
  '/services/delivery/order': typeof homeServicesDeliveryOrderIndexRoute
  '/services/fridge-rentals/order': typeof homeServicesFridgeRentalsOrderIndexRoute
  '/services/storage/order': typeof homeServicesStorageOrderIndexRoute
  '/dashboard/driver/manage-order/$orderId': typeof DashboardDriverManageOrderOrderIdIndexRoute
  '/dashboard/driver/order-details/$orderId': typeof DashboardDriverOrderDetailsOrderIdIndexRoute
  '/dashboard/admin/driver-details/$driverId': typeof DashboardAdmindetailsDriverDetailsDriverIdIndexRoute
  '/dashboard/admin/manage-order/$orderId': typeof DashboardAdmindetailsManageOrderOrderIdIndexRoute
  '/dashboard/admin/order-details/$orderId': typeof DashboardAdmindetailsOrderDetailsOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)': typeof homeRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/driver': typeof DashboardDriverRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(home)/about/': typeof homeAboutIndexRoute
  '/(home)/contact/': typeof homeContactIndexRoute
  '/(home)/drivers/': typeof homeDriversIndexRoute
  '/(home)/services/': typeof homeServicesIndexRoute
  '/(home)/success/': typeof homeSuccessIndexRoute
  '/dashboard/driver/': typeof DashboardDriverIndexRoute
  '/dashboard/user/': typeof DashboardUserIndexRoute
  '/(home)/(auth)/driver-login/': typeof homeauthDriverLoginIndexRoute
  '/(home)/(auth)/driver-registration/': typeof homeauthDriverRegistrationIndexRoute
  '/(home)/(auth)/hra-admin/': typeof homeauthHraAdminIndexRoute
  '/(home)/(auth)/sign-in/': typeof homeauthSignInIndexRoute
  '/(home)/(auth)/sign-up/': typeof homeauthSignUpIndexRoute
  '/(home)/services/delivery/': typeof homeServicesDeliveryIndexRoute
  '/(home)/services/fridge-rentals/': typeof homeServicesFridgeRentalsIndexRoute
  '/(home)/services/storage/': typeof homeServicesStorageIndexRoute
  '/dashboard/admin/drivers/': typeof DashboardAdminDriversIndexRoute
  '/dashboard/admin/orders/': typeof DashboardAdminOrdersIndexRoute
  '/dashboard/admin/payments/': typeof DashboardAdminPaymentsIndexRoute
  '/dashboard/admin/pending-drivers/': typeof DashboardAdminPendingDriversIndexRoute
  '/dashboard/admin/revenue/': typeof DashboardAdminRevenueIndexRoute
  '/dashboard/driver/active-deliveries/': typeof DashboardDriverActiveDeliveriesIndexRoute
  '/dashboard/driver/balance/': typeof DashboardDriverBalanceIndexRoute
  '/dashboard/driver/my-deliveries/': typeof DashboardDriverMyDeliveriesIndexRoute
  '/dashboard/driver/new-deliveries/': typeof DashboardDriverNewDeliveriesIndexRoute
  '/dashboard/user/$reciept/': typeof DashboardUserRecieptIndexRoute
  '/(home)/services/delivery/order/': typeof homeServicesDeliveryOrderIndexRoute
  '/(home)/services/fridge-rentals/order/': typeof homeServicesFridgeRentalsOrderIndexRoute
  '/(home)/services/storage/order/': typeof homeServicesStorageOrderIndexRoute
  '/dashboard/driver/manage-order/$orderId/': typeof DashboardDriverManageOrderOrderIdIndexRoute
  '/dashboard/driver/order-details/$orderId/': typeof DashboardDriverOrderDetailsOrderIdIndexRoute
  '/dashboard/admin/(details)/driver-details/$driverId/': typeof DashboardAdmindetailsDriverDetailsDriverIdIndexRoute
  '/dashboard/admin/(details)/manage-order/$orderId/': typeof DashboardAdmindetailsManageOrderOrderIdIndexRoute
  '/dashboard/admin/(details)/order-details/$orderId/': typeof DashboardAdmindetailsOrderDetailsOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/about'
    | '/contact'
    | '/drivers'
    | '/services'
    | '/success'
    | '/dashboard/driver/'
    | '/dashboard/user'
    | '/driver-login'
    | '/driver-registration'
    | '/hra-admin'
    | '/sign-in'
    | '/sign-up'
    | '/services/delivery'
    | '/services/fridge-rentals'
    | '/services/storage'
    | '/dashboard/admin/drivers'
    | '/dashboard/admin/orders'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pending-drivers'
    | '/dashboard/admin/revenue'
    | '/dashboard/driver/active-deliveries'
    | '/dashboard/driver/balance'
    | '/dashboard/driver/my-deliveries'
    | '/dashboard/driver/new-deliveries'
    | '/dashboard/user/$reciept'
    | '/services/delivery/order'
    | '/services/fridge-rentals/order'
    | '/services/storage/order'
    | '/dashboard/driver/manage-order/$orderId'
    | '/dashboard/driver/order-details/$orderId'
    | '/dashboard/admin/driver-details/$driverId'
    | '/dashboard/admin/manage-order/$orderId'
    | '/dashboard/admin/order-details/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard/admin'
    | '/'
    | '/about'
    | '/contact'
    | '/drivers'
    | '/services'
    | '/success'
    | '/dashboard/driver'
    | '/dashboard/user'
    | '/driver-login'
    | '/driver-registration'
    | '/hra-admin'
    | '/sign-in'
    | '/sign-up'
    | '/services/delivery'
    | '/services/fridge-rentals'
    | '/services/storage'
    | '/dashboard/admin/drivers'
    | '/dashboard/admin/orders'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/pending-drivers'
    | '/dashboard/admin/revenue'
    | '/dashboard/driver/active-deliveries'
    | '/dashboard/driver/balance'
    | '/dashboard/driver/my-deliveries'
    | '/dashboard/driver/new-deliveries'
    | '/dashboard/user/$reciept'
    | '/services/delivery/order'
    | '/services/fridge-rentals/order'
    | '/services/storage/order'
    | '/dashboard/driver/manage-order/$orderId'
    | '/dashboard/driver/order-details/$orderId'
    | '/dashboard/admin/driver-details/$driverId'
    | '/dashboard/admin/manage-order/$orderId'
    | '/dashboard/admin/order-details/$orderId'
  id:
    | '__root__'
    | '/(home)'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/(home)/'
    | '/(home)/about/'
    | '/(home)/contact/'
    | '/(home)/drivers/'
    | '/(home)/services/'
    | '/(home)/success/'
    | '/dashboard/driver/'
    | '/dashboard/user/'
    | '/(home)/(auth)/driver-login/'
    | '/(home)/(auth)/driver-registration/'
    | '/(home)/(auth)/hra-admin/'
    | '/(home)/(auth)/sign-in/'
    | '/(home)/(auth)/sign-up/'
    | '/(home)/services/delivery/'
    | '/(home)/services/fridge-rentals/'
    | '/(home)/services/storage/'
    | '/dashboard/admin/drivers/'
    | '/dashboard/admin/orders/'
    | '/dashboard/admin/payments/'
    | '/dashboard/admin/pending-drivers/'
    | '/dashboard/admin/revenue/'
    | '/dashboard/driver/active-deliveries/'
    | '/dashboard/driver/balance/'
    | '/dashboard/driver/my-deliveries/'
    | '/dashboard/driver/new-deliveries/'
    | '/dashboard/user/$reciept/'
    | '/(home)/services/delivery/order/'
    | '/(home)/services/fridge-rentals/order/'
    | '/(home)/services/storage/order/'
    | '/dashboard/driver/manage-order/$orderId/'
    | '/dashboard/driver/order-details/$orderId/'
    | '/dashboard/admin/(details)/driver-details/$driverId/'
    | '/dashboard/admin/(details)/manage-order/$orderId/'
    | '/dashboard/admin/(details)/order-details/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRouteRoute: typeof homeRouteRouteWithChildren
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardDriverRouteRoute: typeof DashboardDriverRouteRouteWithChildren
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
  DashboardUserRecieptIndexRoute: typeof DashboardUserRecieptIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
      id: '/(home)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user/': {
      id: '/dashboard/user/'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver/': {
      id: '/dashboard/driver/'
      path: '/'
      fullPath: '/dashboard/driver/'
      preLoaderRoute: typeof DashboardDriverIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/(home)/success/': {
      id: '/(home)/success/'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof homeSuccessIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/services/': {
      id: '/(home)/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof homeServicesIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/drivers/': {
      id: '/(home)/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof homeDriversIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/contact/': {
      id: '/(home)/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof homeContactIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/about/': {
      id: '/(home)/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof homeAboutIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/dashboard/user/$reciept/': {
      id: '/dashboard/user/$reciept/'
      path: '/dashboard/user/$reciept'
      fullPath: '/dashboard/user/$reciept'
      preLoaderRoute: typeof DashboardUserRecieptIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver/new-deliveries/': {
      id: '/dashboard/driver/new-deliveries/'
      path: '/new-deliveries'
      fullPath: '/dashboard/driver/new-deliveries'
      preLoaderRoute: typeof DashboardDriverNewDeliveriesIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/dashboard/driver/my-deliveries/': {
      id: '/dashboard/driver/my-deliveries/'
      path: '/my-deliveries'
      fullPath: '/dashboard/driver/my-deliveries'
      preLoaderRoute: typeof DashboardDriverMyDeliveriesIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/dashboard/driver/balance/': {
      id: '/dashboard/driver/balance/'
      path: '/balance'
      fullPath: '/dashboard/driver/balance'
      preLoaderRoute: typeof DashboardDriverBalanceIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/dashboard/driver/active-deliveries/': {
      id: '/dashboard/driver/active-deliveries/'
      path: '/active-deliveries'
      fullPath: '/dashboard/driver/active-deliveries'
      preLoaderRoute: typeof DashboardDriverActiveDeliveriesIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/dashboard/admin/revenue/': {
      id: '/dashboard/admin/revenue/'
      path: '/revenue'
      fullPath: '/dashboard/admin/revenue'
      preLoaderRoute: typeof DashboardAdminRevenueIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/pending-drivers/': {
      id: '/dashboard/admin/pending-drivers/'
      path: '/pending-drivers'
      fullPath: '/dashboard/admin/pending-drivers'
      preLoaderRoute: typeof DashboardAdminPendingDriversIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/payments/': {
      id: '/dashboard/admin/payments/'
      path: '/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof DashboardAdminPaymentsIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/orders/': {
      id: '/dashboard/admin/orders/'
      path: '/orders'
      fullPath: '/dashboard/admin/orders'
      preLoaderRoute: typeof DashboardAdminOrdersIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/drivers/': {
      id: '/dashboard/admin/drivers/'
      path: '/drivers'
      fullPath: '/dashboard/admin/drivers'
      preLoaderRoute: typeof DashboardAdminDriversIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/(home)/services/storage/': {
      id: '/(home)/services/storage/'
      path: '/services/storage'
      fullPath: '/services/storage'
      preLoaderRoute: typeof homeServicesStorageIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/services/fridge-rentals/': {
      id: '/(home)/services/fridge-rentals/'
      path: '/services/fridge-rentals'
      fullPath: '/services/fridge-rentals'
      preLoaderRoute: typeof homeServicesFridgeRentalsIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/services/delivery/': {
      id: '/(home)/services/delivery/'
      path: '/services/delivery'
      fullPath: '/services/delivery'
      preLoaderRoute: typeof homeServicesDeliveryIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/(auth)/sign-up/': {
      id: '/(home)/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof homeauthSignUpIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/(auth)/sign-in/': {
      id: '/(home)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof homeauthSignInIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/(auth)/hra-admin/': {
      id: '/(home)/(auth)/hra-admin/'
      path: '/hra-admin'
      fullPath: '/hra-admin'
      preLoaderRoute: typeof homeauthHraAdminIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/(auth)/driver-registration/': {
      id: '/(home)/(auth)/driver-registration/'
      path: '/driver-registration'
      fullPath: '/driver-registration'
      preLoaderRoute: typeof homeauthDriverRegistrationIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/(auth)/driver-login/': {
      id: '/(home)/(auth)/driver-login/'
      path: '/driver-login'
      fullPath: '/driver-login'
      preLoaderRoute: typeof homeauthDriverLoginIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/dashboard/driver/order-details/$orderId/': {
      id: '/dashboard/driver/order-details/$orderId/'
      path: '/order-details/$orderId'
      fullPath: '/dashboard/driver/order-details/$orderId'
      preLoaderRoute: typeof DashboardDriverOrderDetailsOrderIdIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/dashboard/driver/manage-order/$orderId/': {
      id: '/dashboard/driver/manage-order/$orderId/'
      path: '/manage-order/$orderId'
      fullPath: '/dashboard/driver/manage-order/$orderId'
      preLoaderRoute: typeof DashboardDriverManageOrderOrderIdIndexRouteImport
      parentRoute: typeof DashboardDriverRouteRoute
    }
    '/(home)/services/storage/order/': {
      id: '/(home)/services/storage/order/'
      path: '/services/storage/order'
      fullPath: '/services/storage/order'
      preLoaderRoute: typeof homeServicesStorageOrderIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/services/fridge-rentals/order/': {
      id: '/(home)/services/fridge-rentals/order/'
      path: '/services/fridge-rentals/order'
      fullPath: '/services/fridge-rentals/order'
      preLoaderRoute: typeof homeServicesFridgeRentalsOrderIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/(home)/services/delivery/order/': {
      id: '/(home)/services/delivery/order/'
      path: '/services/delivery/order'
      fullPath: '/services/delivery/order'
      preLoaderRoute: typeof homeServicesDeliveryOrderIndexRouteImport
      parentRoute: typeof homeRouteRoute
    }
    '/dashboard/admin/(details)/order-details/$orderId/': {
      id: '/dashboard/admin/(details)/order-details/$orderId/'
      path: '/order-details/$orderId'
      fullPath: '/dashboard/admin/order-details/$orderId'
      preLoaderRoute: typeof DashboardAdmindetailsOrderDetailsOrderIdIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/(details)/manage-order/$orderId/': {
      id: '/dashboard/admin/(details)/manage-order/$orderId/'
      path: '/manage-order/$orderId'
      fullPath: '/dashboard/admin/manage-order/$orderId'
      preLoaderRoute: typeof DashboardAdmindetailsManageOrderOrderIdIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/(details)/driver-details/$driverId/': {
      id: '/dashboard/admin/(details)/driver-details/$driverId/'
      path: '/driver-details/$driverId'
      fullPath: '/dashboard/admin/driver-details/$driverId'
      preLoaderRoute: typeof DashboardAdmindetailsDriverDetailsDriverIdIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  homeAboutIndexRoute: typeof homeAboutIndexRoute
  homeContactIndexRoute: typeof homeContactIndexRoute
  homeDriversIndexRoute: typeof homeDriversIndexRoute
  homeServicesIndexRoute: typeof homeServicesIndexRoute
  homeSuccessIndexRoute: typeof homeSuccessIndexRoute
  homeauthDriverLoginIndexRoute: typeof homeauthDriverLoginIndexRoute
  homeauthDriverRegistrationIndexRoute: typeof homeauthDriverRegistrationIndexRoute
  homeauthHraAdminIndexRoute: typeof homeauthHraAdminIndexRoute
  homeauthSignInIndexRoute: typeof homeauthSignInIndexRoute
  homeauthSignUpIndexRoute: typeof homeauthSignUpIndexRoute
  homeServicesDeliveryIndexRoute: typeof homeServicesDeliveryIndexRoute
  homeServicesFridgeRentalsIndexRoute: typeof homeServicesFridgeRentalsIndexRoute
  homeServicesStorageIndexRoute: typeof homeServicesStorageIndexRoute
  homeServicesDeliveryOrderIndexRoute: typeof homeServicesDeliveryOrderIndexRoute
  homeServicesFridgeRentalsOrderIndexRoute: typeof homeServicesFridgeRentalsOrderIndexRoute
  homeServicesStorageOrderIndexRoute: typeof homeServicesStorageOrderIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  homeAboutIndexRoute: homeAboutIndexRoute,
  homeContactIndexRoute: homeContactIndexRoute,
  homeDriversIndexRoute: homeDriversIndexRoute,
  homeServicesIndexRoute: homeServicesIndexRoute,
  homeSuccessIndexRoute: homeSuccessIndexRoute,
  homeauthDriverLoginIndexRoute: homeauthDriverLoginIndexRoute,
  homeauthDriverRegistrationIndexRoute: homeauthDriverRegistrationIndexRoute,
  homeauthHraAdminIndexRoute: homeauthHraAdminIndexRoute,
  homeauthSignInIndexRoute: homeauthSignInIndexRoute,
  homeauthSignUpIndexRoute: homeauthSignUpIndexRoute,
  homeServicesDeliveryIndexRoute: homeServicesDeliveryIndexRoute,
  homeServicesFridgeRentalsIndexRoute: homeServicesFridgeRentalsIndexRoute,
  homeServicesStorageIndexRoute: homeServicesStorageIndexRoute,
  homeServicesDeliveryOrderIndexRoute: homeServicesDeliveryOrderIndexRoute,
  homeServicesFridgeRentalsOrderIndexRoute:
    homeServicesFridgeRentalsOrderIndexRoute,
  homeServicesStorageOrderIndexRoute: homeServicesStorageOrderIndexRoute,
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(
  homeRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminDriversIndexRoute: typeof DashboardAdminDriversIndexRoute
  DashboardAdminOrdersIndexRoute: typeof DashboardAdminOrdersIndexRoute
  DashboardAdminPaymentsIndexRoute: typeof DashboardAdminPaymentsIndexRoute
  DashboardAdminPendingDriversIndexRoute: typeof DashboardAdminPendingDriversIndexRoute
  DashboardAdminRevenueIndexRoute: typeof DashboardAdminRevenueIndexRoute
  DashboardAdmindetailsDriverDetailsDriverIdIndexRoute: typeof DashboardAdmindetailsDriverDetailsDriverIdIndexRoute
  DashboardAdmindetailsManageOrderOrderIdIndexRoute: typeof DashboardAdmindetailsManageOrderOrderIdIndexRoute
  DashboardAdmindetailsOrderDetailsOrderIdIndexRoute: typeof DashboardAdmindetailsOrderDetailsOrderIdIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminDriversIndexRoute: DashboardAdminDriversIndexRoute,
  DashboardAdminOrdersIndexRoute: DashboardAdminOrdersIndexRoute,
  DashboardAdminPaymentsIndexRoute: DashboardAdminPaymentsIndexRoute,
  DashboardAdminPendingDriversIndexRoute:
    DashboardAdminPendingDriversIndexRoute,
  DashboardAdminRevenueIndexRoute: DashboardAdminRevenueIndexRoute,
  DashboardAdmindetailsDriverDetailsDriverIdIndexRoute:
    DashboardAdmindetailsDriverDetailsDriverIdIndexRoute,
  DashboardAdmindetailsManageOrderOrderIdIndexRoute:
    DashboardAdmindetailsManageOrderOrderIdIndexRoute,
  DashboardAdmindetailsOrderDetailsOrderIdIndexRoute:
    DashboardAdmindetailsOrderDetailsOrderIdIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardDriverRouteRouteChildren {
  DashboardDriverIndexRoute: typeof DashboardDriverIndexRoute
  DashboardDriverActiveDeliveriesIndexRoute: typeof DashboardDriverActiveDeliveriesIndexRoute
  DashboardDriverBalanceIndexRoute: typeof DashboardDriverBalanceIndexRoute
  DashboardDriverMyDeliveriesIndexRoute: typeof DashboardDriverMyDeliveriesIndexRoute
  DashboardDriverNewDeliveriesIndexRoute: typeof DashboardDriverNewDeliveriesIndexRoute
  DashboardDriverManageOrderOrderIdIndexRoute: typeof DashboardDriverManageOrderOrderIdIndexRoute
  DashboardDriverOrderDetailsOrderIdIndexRoute: typeof DashboardDriverOrderDetailsOrderIdIndexRoute
}

const DashboardDriverRouteRouteChildren: DashboardDriverRouteRouteChildren = {
  DashboardDriverIndexRoute: DashboardDriverIndexRoute,
  DashboardDriverActiveDeliveriesIndexRoute:
    DashboardDriverActiveDeliveriesIndexRoute,
  DashboardDriverBalanceIndexRoute: DashboardDriverBalanceIndexRoute,
  DashboardDriverMyDeliveriesIndexRoute: DashboardDriverMyDeliveriesIndexRoute,
  DashboardDriverNewDeliveriesIndexRoute:
    DashboardDriverNewDeliveriesIndexRoute,
  DashboardDriverManageOrderOrderIdIndexRoute:
    DashboardDriverManageOrderOrderIdIndexRoute,
  DashboardDriverOrderDetailsOrderIdIndexRoute:
    DashboardDriverOrderDetailsOrderIdIndexRoute,
}

const DashboardDriverRouteRouteWithChildren =
  DashboardDriverRouteRoute._addFileChildren(DashboardDriverRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardDriverRouteRoute: DashboardDriverRouteRouteWithChildren,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
  DashboardUserRecieptIndexRoute: DashboardUserRecieptIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
